### ISSUE TITLE
Should we find a way to enforce uniqueness of action types?

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/ts-react-boilerplate#132]
Seemingly others try to solve [this](https://github.com/reactjs/redux/issues/786) too. Right now we prefix action type by its module name which should be sufficient enough. However since we are using Typescript, we can probably do better?

**Comment by cyberhck** [comment]
Let's revisit this because now we have action creators with a separate package, we can easily do this via lint :)

**Comment by paibamboo** [comment]
Yes, thinking the same

**Comment by paibamboo** [comment]
https://github.com/crazyfactory/tslint-rules is updated, but the npm package still private, wating for @Solomonic to make it public

**Comment by cyberhck** [comment]
But github is public I thought we published public as well :thinking:
