### ISSUE TITLE
Simplify things

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/ts-react-boilerplate#219]
Too opinionated, hard to use from the get go.

- restructure `action` typings
  - remove `IState<P, M>`
  - remove `meta`
  - simplify action's `payload`, no need to be same type as state
- get rid of redux-form (redux store and its extra typings are too complicated for just a simple form)
- testing full saga (instead of testing each step which is easy to break)

**Comment by cyberhck** [comment]
> get rid of redux-form
I've been wanting that for so long.
