### ISSUE TITLE
Drop Wallaby

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/ts-react-boilerplate#231]
We don't have subscription for Wallaby anymore, and Jest has been updated quite far since last time we set up Wallaby. Right now our outdated Wallaby is breaking, and there's nothing we can do with it.

CC @cyberhck

**Comment by cyberhck** [comment]
I'm in verge of buying my own wallaby license. It's okay if you want to drop it, it shouldn't be that hard for people to integrate again.
