### ISSUE TITLE
Upgrade router5 to v7

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/ts-react-boilerplate#233]
But we need to set `esModuleInterop` to `true` in tsconfig.json because the way router5 imports react
```
import React from "react"
```
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html for more info about `esModuleInterop`

**Comment by cyberhck** [comment]
can't we tell typescript to ignore anything inside `node_modules`?

**Comment by paibamboo** [comment]
As far as I know, we can't exclude it if our codes reference to it.
As mentioned [in the faq](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler)
> if the file was found, it will be included regardless if it was excluded in the previous steps.

An alternative is to use `skipLibCheck` but that will exclude all `*.d.ts` files.

**Comment by cyberhck** [comment]
weird, I'm okay with enabling esModuleInterop, but maybe we should write a lint rule which forces react import to have only 1 way?

**Comment by paibamboo** [comment]
FYI, we still need to use the pattern `import * as React from "react";` because styleguidist does not work when we du `import React from "react"`

**Comment by paibamboo** [comment]
Closed by #251
