### ISSUE TITLE
imports got screwed up

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/ts-react-boilerplate#242]
https://github.com/crazyfactory/ts-react-boilerplate/blob/51d82dcbb189cd7f599d64890ee1836539d472d8/tsconfig.json#L3-L9

Not sure why they are there, and it did use to work, now when I import, it's trying to use absolute path from app directory, and tslint rule obviously complains saying that package isn't listed in package.json, I kinda prefer the relative import (webstorm used to import relative by default before), I remove these lines on my setup and everything works like a charm, let me know if you're okay with removing it so I can send a PR.

**Comment by paibamboo** [comment]
Yes, those are supposed to be removed. It used to work but does not work now because PHPStorm gets smarter. Please send a pr :)
