### ISSUE TITLE
Linting: False negative for rules excluded in overrides on unmatched files

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/ts-react-boilerplate#280]
This seems like a bug in `eslint-plugin-tslint`. Please follow this [issue](https://github.com/typescript-eslint/typescript-eslint/issues/1031)

**Comment by cyberhck** [comment]
yes, react-this-binding issue is working on IDE (however the option to detect `@autobind` isn't working), but on terminal there's nothing.

**Comment by paibamboo** [comment]
Closed by #338
