### ISSUE TITLE
Bring back ts-optchain's oc

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/ts-react-boilerplate#282]
In the past, we used [ts-optchain](https://github.com/rimeto/ts-optchain)'s oc, but we found a bug (it cannot refer a type of properties or sub properties in some specific cases), so we fixed it [here](https://github.com/crazyfactory/ts-react-boilerplate/blob/master/src/app/helpers/oc.ts) but never sent a pr. Apparently that bug which I don't remember has been fixed, so we can bring it back.

**Comment by sanketmaru** [comment]
I would like to take this issue and contribute to this project.

**Comment by cyberhck** [comment]
@sanketmaru feel free to do it :) let us know if you need any help.

**Comment by sanketmaru** [comment]
I have included ts-optchain as a dev dependency and changed the code in 

https://github.com/crazyfactory/ts-react-boilerplate/blob/master/src/app/selectors/translationsSelector.ts as its using util file. 

I can see the build file has ts-optchain changes, but wanted to test from functionality point of view. 
Can you help with this ?

**Comment by cyberhck** [comment]
why dev-dependency?

**Comment by sanketmaru** [comment]
I was thinking to include the babel plugin which will transpile the code during build itself.

**Comment by cyberhck** [comment]
nice, I didn't know about that plugin, but I think we're not using babel-plugin as of now.

**Comment by sanketmaru** [comment]
ok , i would raise PR with adding as a dependency for now then. 
Can you tell me in code if anywhere i can test this out and use OC ? If not i will just replace in one reference found.

**Comment by cyberhck** [comment]
for testing, you can write a simple test case.
