### ISSUE TITLE
yes, hmr sometimes doesn't work

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/ts-react-boilerplate#297]
not sure why, but sometimes it doesn't work, and sometimes it randomly does.

There's also a new warning thrown by HMR now a days for new version of react warning, we need to fix that as well:
> react-hot-loader.development.js:2429 React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work

**Comment by paibamboo** [comment]
Would be nice if you have reproducing steps :)

**Comment by cyberhck** [comment]
Sorry, didn't add steps, thought you were aware,

- `git clone git@github.com/crazyfactory/ts-react-boilerplate hmr`
- `cd hmr`
- `npm i`
- `npm start`
- start browser, go to http://localhost:8889
- open devtools, go to console,

# expected behavior:
no warnings,

# actual behavior:
![image](https://user-images.githubusercontent.com/3640284/68099336-8d715180-fef4-11e9-870c-550af957d109.png)

This will only give you the warning, but for some reason this time HMR is working, I have another project that doesn't work, it's quite random, it's almost like: `if ((Math.floor(Math.random() * 100)) % 5 === 0) dontWork();`

**Comment by paibamboo** [comment]
I'm aware of the warning, but never encountered broken hmr..

**Comment by cyberhck** [comment]
I haven't seen it not working for quite a while, I'll open it later if I find it, but I don't see that likely, also it always worked on ubuntu, and the non working only happened sometimes, and only on windows, so I don't really care ¯\_(ツ)_/¯ 🙂 but now it's working 100% of the time.
