### ISSUE TITLE
bring back wallaby config

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/ts-react-boilerplate#348]
I was about to write tests and run them, when I realized there's no wallaby.js file anymore, let's bring it back :)

**Comment by paibamboo** [comment]
We don't have any wallaby license anymore.. if you do please feel free to create a pr

**Comment by cyberhck** [comment]
I do have a wallabyjs, btw, so do you, it's a perpetual fallback for your life :) (I'm renewing my license this weekend) I'll send a PR :)

**Comment by cyberhck** [comment]
I'm gonna do this as part of hacktoberfest

**Comment by cyberhck** [comment]
closes by #353
