### ISSUE TITLE
move to snyk.io

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/ts-react-boilerplate#355]
Greenkeeper is saying good-bye. Once #354 is closed, let's move to https://snyk.io

**Comment by paibamboo** [comment]
@z3niths Can you please grant snyk permission to create a pull request to this repository?

**Comment by cyberhck** [comment]
the first part of this is done, but for non security related stuff, we'd like it to say "chore" instead of "fix", once we either figure out it's not possible, or we configure it that way, then we can close this issue.

if it's not possible, we should try to create a next branch, and merge everything there instead, and once we need a release then we can merge next into master I guess?

cc @paibamboo

**Comment by z3niths** [comment]
I've tried to find a way to configure the commit message but still cannot see a place I can do.
Please lemme know if you have any possibility to do that.

**Comment by cyberhck** [comment]
I'll try to search around, it's not the end of the world, for non secure stuff, we can merge to a next branch first, (and it doesn't matter for this repo, for tinka we'll need to do it that way)

**Comment by cyberhck** [comment]
now that snyk is active and sending good upgrade, I'll close this issue thanks @z3niths 🙂
