### ISSUE TITLE
Should we deprecate ts-react-boilerplate

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/ts-react-boilerplate#472]
While it's been a good run and back in the days redux saga and redux were great players and this was one of the best SSR + TypeScript React starter kit out there.

I think it's safe to say that even crazy factory won't be using this starter kit and would go for nextjs instead.

I think this project helped us a lot back then, I don't see a reasonable argument to continue keeping this project like this.

Keeping it open and not contributing just ensures our dependencies go out of date, or it'll require us to maintain this and make sure it's optimized, when brilliant developers at vercel are getting paid to maintain nextjs. I think they're doing a very good job.

So my proposal is to:
- Add in readme that this project is deprecated in favor of nextjs
- Start closing all issues (with the message)
- Lock all issue conversations
- close all pull requests (with the message)
- lock all PR conversations
- archive this project.

**Comment by cyberhck** [comment]
I can send PR to add things on readme and close all issues if you give me a go-ahead. Please discuss internally and see if everyone agrees :slightly_smiling_face:

**Comment by paibamboo** [comment]
Please go ahead Nishchal. Thanks for your contribution!
